Squid:
  image: sameersbn/squid:3.5.27-1
  ports:
    - "3128:3128"
  volumes:
    - /srv/docker/squid/cache:/var/spool/squid
    - ./:/root
    - ./squid.conf:/etc/squid/squid.conf
  restart: always
