version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: login aws ecr
          command: |

            login="$(aws ecr get-login --no-include-email)"
            ${login}
      - run:
          name: docker-compose up
          command: |
            ./build-push.sh